default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: quiz_master_development

test:
  <<: *default
  database: quiz_master_test

production:
  <<: *default
  database: quiz_master_production
  username: quiz_master
  password: <%= ENV['QUIZ_MASTER_DATABASE_PASSWORD'] %>
